version: "3"
services:
  nginx: #服务名称
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    # container_name: nginx1
    ports:
    - "${NGINX_HTTP_HOST_PORT}:80"
    - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
    - ${SOURCE_DIR}:/www/:rw
    - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
    - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
    - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    - ${NGINX_SSL_CERTIFICATE_DIR}:/etc/nginx/ssl:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
    - default


networks:
  default:
